### PR TITLE
Added functions for PQ, SF, and FB

### PR DESCRIPTION
**Pull request by comsma**
I implemented a few more ZPL commands and defined functions for them.

### CODE REVIEW

**Comment by SmolSoftBoi** [comment]
What ZPL documentation have you referenced?

**Comment by comsma** [comment]
I was working off of 

https://www.zebra.com/content/dam/zebra_new_ia/en-us/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf

**Comment by SmolSoftBoi** [comment]
Have you tested the results of your added functions in print? I can see some discrepancies from the documentation.

**Comment by SmolSoftBoi** [comment]
There's also a lot of documentation that's been removed. Any reason why?

**Comment by comsma** [comment]
My bad, I thought the comments were redundant but now I realize it's when you want to use the commands separately. I will add them back and do some testing with a ZTC ZT411 printer. I also am adding in the B3 barcode command. I could implement more if you want but for now I was just implementing the functionality I needed.

**Comment by SmolSoftBoi** [comment]
If you'd prefer to open issues with the functions you require, I can add those in.

**Comment by SmolSoftBoi** [comment]
I've added these commands to the master, please test them, and I'll create a release.

**Pull request closed without merging**
